import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-black py-2">
        <ModeToggle />
        <p className="text-lg mt-4 text-black dark:text-white">
          Hello, this is a sample page with a theme toggle button.
        </p>
      </div>
    </>
  );
}
